spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

redis:
  database: DClinicRedis
  password: aagjYEGlik0AfrPeQM9lsS3v51fviN8a
  host: edis-12598.c302.asia-northeast1-1.gce.cloud.redislabs.com
  port: 12598


---
environment: test
redis:
  host: localhost
  port: 6380
  password: